In [35]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'
tf.reset_default_graph()

In [36]:
#Preprocessing 
df=pd.read_csv('HeartDisease.csv')
num_sapmles=270
shuffle_df=df.sample(frac=1)
outputs=shuffle_df[['num']]
no_samples=outputs.shape[0]
print(no_samples)
inputs=shuffle_df.drop(['num','thalach','exang','oldpeak','Place','thalach','Age','Sex','ID'],axis=1)

457

In [37]:
inputs.isnull().sum()

cp           0
trestbps    33
chol        26
fbs         54
restecg      2
dtype: int64

In [38]:
inputs['trestbps']=inputs['trestbps'].fillna(np.mean(inputs['trestbps']))
inputs['fbs']=inputs['fbs'].fillna(np.mean(inputs['fbs']))
inputs['cp']=inputs['cp'].fillna(np.mean(inputs['cp']))
inputs['chol']=inputs['chol'].fillna(np.mean(inputs['chol']))
inputs['restecg']=inputs['restecg'].fillna(np.mean(inputs['restecg']))

In [39]:
inputs

     cp    trestbps        chol       fbs  restecg
310   2  130.000000    0.000000  0.138958      1.0
309   4  130.000000    0.000000  0.138958      1.0
272   4  150.000000  230.000000  0.000000      1.0
115   4  150.000000  215.000000  0.000000      0.0
411   2  131.488208  283.000000  0.000000      0.0
448   4  130.000000  207.000000  0.000000      1.0
360   4  128.000000    0.000000  1.000000      1.0
311   3  105.000000    0.000000  0.000000      0.0
287   4  140.000000  341.000000  0.000000      1.0
136   3  120.000000  195.000000  0.000000      0.0
255   1  140.000000  272.000000  1.000000      0.0
262   4  130.000000  298.000000  0.000000      0.0
180   3  130.000000  318.000000  0.000000      0.0
58    4  140.000000  358.000000  0.000000      0.0
23    2  130.000000  283.000000  0.000000      1.0
151   2  160.000000  195.000000  0.000000      1.0
231   4  120.000000  231.000000  0.000000      0.0
217   4  125.000000  224.000000  0.000000      0.0
202   4  118.000000  186.000000  0.000000      0.0
341   4  115.000000    0.000000  0.000000      0.0
300   4  150.000000    0.000000  0.138958      0.0
312   3  160.000000    0.000000  0.138958      2.0
238   4  120.000000  182.000000  0.000000      0.0
336   4  115.000000    0.000000  0.138958      0.0
320   4  140.000000    0.000000  0.138958      0.0
76    4  120.000000  225.000000  0.000000      0.0
270   4  145.000000  248.000000  0.000000      0.0
239   4  170.000000  200.048724  0.000000      0.0
175   2  130.000000  251.000000  0.000000      0.0
27    2  120.000000  275.000000  0.138958      0.0
..   ..         ...         ...       ...      ...
62    2  120.000000  249.000000  0.000000      1.0
370   4  131.488208  203.000000  1.000000      0.0
412   4  131.488208  211.000000  0.000000      0.0
181   3  180.000000  213.000000  0.000000      0.0
447   4  130.000000  203.000000  1.000000      0.0
429   4  140.000000  274.000000  0.000000      0.0
277   4  170.000000  263.000000  1.000000      0.0
395   3  131.488208  245.000000  1.000000      1.0
69    2  130.000000  215.000000  0.000000      0.0
53    2  120.000000  196.000000  0.000000      0.0
384   4  130.000000  311.000000  0.138958      1.0
137   4  124.000000  260.000000  0.000000      1.0
338   4  185.000000    0.000000  0.000000      0.0
418   4  138.000000  274.000000  0.000000      0.0
66    2  142.000000  207.000000  0.000000      0.0
99    2  140.000000  238.000000  0.000000      0.0
109   2  110.000000  202.000000  0.000000      0.0
47    2  130.000000  245.000000  0.000000      0.0
453   4  127.000000  333.000000  1.000000      1.0
305   3  110.000000    0.000000  0.138958      0.0
377   3  120.000000    0.000000  0.000000      1.0
313   4  120.000000    0.000000  0.138958      0.0
244   4  140.000000  200.048724  0.000000      0.0
266   4  180.000000  285.000000  0.000000      1.0
276   4  140.000000  264.000000  1.000000      2.0
376   3  134.000000  240.000000  0.138958      0.0
304   4  115.000000    0.000000  0.000000      0.0
173   2  140.000000  260.000000  1.000000      0.0
298   3  100.000000    0.000000  0.138958      0.0
186   1  160.000000  193.000000  0.000000      0.0

[457 rows x 5 columns]

In [40]:
inputs.isnull().sum()

cp          0
trestbps    0
chol        0
fbs         0
restecg     0
dtype: int64

In [ ]:
tf.